### PR TITLE
[WIP] Upgrade to lego@v2

### LINKED ISSUE #11: ACME renewal querying wrong NS
I have a private and public Route53 Zone of the same domain, and during renewal it adds the challenge to the public zone, but to verify, it's asking the private zone... therefore Route53 returns REFUSED.

```
acme_certificate.acme_wildcard: Modifying... (ID: https://acme-v02.api.letsencrypt.org/ac...t/...)
...
acme_certificate.acme_wildcard: Still modifying... (ID: https://acme-v02.api.letsencrypt.org/ac...t/..., 1m50s elapsed)
acme_certificate.acme_wildcard: Still modifying... (ID: https://acme-v02.api.letsencrypt.org/ac...t/..., 2m0s elapsed)
acme_certificate.acme_wildcard: Still modifying... (ID: https://acme-v02.api.letsencrypt.org/ac...t/..., 2m10s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* acme_certificate.acme_wildcard: 1 error(s) occurred:

* acme_certificate.acme_wildcard: acme: Error -> One or more domains had a problem:
[host.domain.tld] Time limit exceeded. Last error: NS ns-512.awsdns-00.net. returned REFUSED for _acme-challenge.domain.tld.
```

I looked into my zones and noticed that `ns-512.awsdns-00.net` is only on my private zone, not on the public zone. Is there a way to control this?

### LINKED ISSUE #15: Update lego library to v2
Bug fixes in `github.com/xenolf/lego` are only being applied to the latest version, which has many breaking API changes. I'm working on adapting this provider to use the new API.

### PR DESCRIPTION
**Pull request by bzub**
Fixes #15, possibly others like #11, https://github.com/xenolf/lego/issues/375, etc.
Supersedes #10 

TODO:
- [x] Update code for new lego API
- [x] `go mod tidy`
- [x] Run acceptance tests
- [ ] Merge #17 + rebase
- [ ] Update docs, GNUMakefile, scripts, etc

### CODE REVIEW

**Comment by mengesb** [comment]
@bzub - could you point to the fix in code where you might have a solution for [xenolf/lego#375](https://github.com/xenolf/lego/issues/375)?

Also I know that @vancluever gave me some outlines on how to get a PR accepted and moved on via our pTFE contacts. I recall one commit (squashed) for the code change base, another commit for the documentation updates --  I don't recall if there was more. Could you elaborate @vancluever ?

**Comment by vancluever** [comment]
@mengesb @bzub indeed when I'm pulling in updates to lego I do an audit of new providers to make sure they are added appropriately and documentation is included.

What I will probably do is continue the work here and in #17 to make sure this is all cleared up. I'll probably review docs at this point in time, which should be a non-issue given that the new provider count is not _too_ overwhelming (#10 helped with this, looks like there's only 9 new providers to add).

**Comment by mengesb** [comment]
@vancluever - thank you so much for spending time on this; as you can tell it's very important to me and quite likely others!

What updates to this PR need to happen since #10 was merged; it was cited by @bzub that this supersedes #10 so i'm sure that the conflicts present (namely around exoscale/egoscale) need to be resolved, but you also cited #17 which may also clean that up as well.

If you need someone to test this I'm certainly willing to see if this will work given my situation.

**Comment by vancluever** [comment]
@bzub thanks again for this - I've made a few edits on top of the work here but it largely looked good and having the necessary API updates done was very useful.

I can add the documentation for the outstanding providers.

@mengesb in regards to xenolf/lego#375, I will be adding a new `nameservers` option (or something similarly named) to the `dns_challenge` block that will set the preferred DNS servers. That should fully address #11.

**Pull request merged**
