### PR TITLE
Use Go modules for dependency management

### LINKED ISSUE #16: Use Go modules for dependencies
[Go modules](https://github.com/golang/go/wiki/Modules) are the new new. I find it's a much more intuitive and less error-prone dependency system than dep, etc. The main terraform project uses them, as well as other providers switching to them.

I'm working on this.

### PR DESCRIPTION
**Pull request by bzub**
Fixes #16.

TODO:
- [x] `go mod init`
- [x] Delete `Gopkg.*` and `vendor/`
- [x] `go mod tidy`
- [x] Make sure it builds
- [x] Run acceptance tests
- [x] Merge #14 + rebase
- [x] Update docs, GNUMakefile, scripts, etc

### CODE REVIEW

**Comment by bzub** [comment]
Acceptance tests pass: https://gist.github.com/bzub/4edae7498d95f1d0c6d32948939f689d

**Comment by bzub** [comment]
Ready for review/merge. @vancluever

**Comment by vancluever** [comment]
Thanks for this @bzub.

I'll try and keep the work here as much as possible. Another rebase will be necessary as #10 was merged too, but I'd imagine that will be a non-issue.

Also, one thing I will be adding to this is we will be vendoring the dependencies as per before, so the content in `vendor` will be re-added, as per #24.

**Comment by vancluever** [comment]
@bzub thanks a lot for this work - indeed everything looks good!

**Pull request merged**
